//
// Created by blast on 2021/5/29.
//

//Add a string you have to chang, .c, .h, totalstr, *strs[]

#include "Language.h"
#include <string.h>
#include <stdio.h>
#define TOTALSTRS 72


char MAIN_SINGLE[20];
char MAIN_MULTI[20];
char MAIN_SETTING[10];
char MAIN_EXIT[10];
char MAIN_DIFFICULTY[20];
char SETTING_SOUND[10];
char SETTING_LANGUAGE[10];
char SETTING_WINDOW[20];
char SETTING_BACK[10];
char SETTING_LANG_ENGLISH[10];
char SETTING_LANG_CHINESE[10];
char LOOP_4_PLAYERS[20];
char LOOP_3_PLAYERS[20];
char LOOP_2_PLAYERS[20];
char CAREER_BUILDER[20];
char CAREER_COUNCILOR[20];
char CAREER_PRUDUCER[20];
char CAREER_PROSPECTOR[20];
char CAREER_TRADER[20];
char CARD_AQUEDUCT[20];
char CARD_ARCHIVE[20];
char CARD_BLACKMARKET[20];
char CARD_CARPENTER[20];
char CARD_CHAPEL[20];
char CARD_COFFEESOASTER[20];
char CARD_CRANE[20];
char CARD_CITYHALL[20];
char CARD_GUILDHALL[20];
char CARD_GOLDMINE[20];
char CARD_HERO[20];
char CARD_INDIGOPLANT[20];
char CARD_LIBRARY[20];
char CARD_MARKETSTAND[20];
char CARD_MARKETHALL[20];
char CARD_PREFECTURE[20];
char CARD_POORHOUSE[20];
char CARD_PALACE[20];
char CARD_QUARRY[20];
char CARD_SILVER_SMELTER[20];
char CARD_SUGARMILL[20];
char CARD_STATUS[20];
char CARD_SMITHY[20];
char CARD_TOBACCOSTORAGE[20];
char CARD_TRADINGPOST[20];
char CARD_TRIUMPHALARCH[20];
char CARD_TOWER[20];
char CARD_VICTORYCOLUMN[20];
char CARD_WELL[20];
char PH_TRADER_TEXT[40];
char PH_BUILDER_TEXT[40];
char PH_PROSPECTOR_TEXT[40];
char PH_COUNCILLOR_TEXT[40];
char PH_ROUND_TEXT[40];
char PH_DISCARD_TEXT[40];
char PH_PRODUCER_TEXT[40];
char PH_CHOOSE_CAREER_TEXT[40];
char PH_GAME_END_TEXT[40];
char PH_CHOOSECARD_TEXT[40];
char BUTTON_CONFIRM_TEXT[10];
char MSG_BUILDER_TEXT[40];
char MSG_TRADER_TEXT[40];
char MSG_PRODUCER_TEXT[40];
char MSG_COUNCILLOR_TEXT[40];
char MSG_CHOOSECAREER_TEXT[40];
char MSG_DISCARD_TEXT[40];
char MSG_PROSPECTOR_TEXT[40];
char MSG_GAMEEND_TEXT[40];
char MSG_GOVERNER_TEXT[40];
char MSG_CHOOSECARD_TEXT[40];
char BUTTON_YES_TEXT[10];
char BUTTON_NO_TEXT[10];
char USE_CRANE_TEXT[40];


char *strs[] = {MAIN_SINGLE, MAIN_MULTI, MAIN_SETTING, MAIN_EXIT, MAIN_DIFFICULTY,
                SETTING_SOUND, SETTING_LANGUAGE, SETTING_WINDOW, SETTING_BACK, SETTING_LANG_ENGLISH, SETTING_LANG_CHINESE,
                LOOP_4_PLAYERS, LOOP_3_PLAYERS, LOOP_2_PLAYERS, CAREER_BUILDER, CAREER_COUNCILOR, CAREER_PRUDUCER, CAREER_PROSPECTOR, CAREER_TRADER,
                CARD_AQUEDUCT, CARD_ARCHIVE, CARD_BLACKMARKET, CARD_CARPENTER, CARD_CHAPEL, CARD_COFFEESOASTER, CARD_CRANE, CARD_CITYHALL,
                CARD_GUILDHALL, CARD_GOLDMINE, CARD_HERO, CARD_INDIGOPLANT, CARD_LIBRARY, CARD_MARKETHALL, CARD_MARKETHALL, CARD_PREFECTURE,
                CARD_POORHOUSE, CARD_PALACE, CARD_QUARRY, CARD_SILVER_SMELTER, CARD_SUGARMILL, CARD_STATUS, CARD_SMITHY, CARD_TOBACCOSTORAGE,
                CARD_TRADINGPOST, CARD_TRIUMPHALARCH, CARD_TOWER, CARD_VICTORYCOLUMN, CARD_WELL,
                PH_TRADER_TEXT, PH_BUILDER_TEXT, PH_PROSPECTOR_TEXT, PH_COUNCILLOR_TEXT, PH_ROUND_TEXT, PH_DISCARD_TEXT, PH_PRODUCER_TEXT, PH_CHOOSE_CAREER_TEXT, PH_GAME_END_TEXT, PH_CHOOSECARD_TEXT,
                BUTTON_CONFIRM_TEXT,
                MSG_BUILDER_TEXT, MSG_TRADER_TEXT, MSG_PRODUCER_TEXT, MSG_COUNCILLOR_TEXT, MSG_CHOOSECAREER_TEXT, MSG_DISCARD_TEXT, MSG_PROSPECTOR_TEXT, MSG_GAMEEND_TEXT, MSG_GOVERNER_TEXT, MSG_CHOOSECARD_TEXT,
                BUTTON_YES_TEXT, BUTTON_NO_TEXT, USE_CRANE_TEXT};

static char langPath[120];


void set_language(char *lang){
    strcpy(langPath, "./Asset/Language/");
    strcpy(&langPath[strlen(langPath)], lang);
}

void load_language(){
    FILE *langFile = fopen(langPath, "r");
    char tmp[10000];
    for(int i = 0; i < TOTALSTRS; ++i) {
        fgets(tmp, 10000, langFile);
        tmp[strlen(tmp) - 1] = '\0';
        strcpy(strs[i], tmp);
    }
    fclose(langFile);
}

