//
// Created by blast on 2021/5/26.
//

#ifndef COMPUTER_PROGRAMMING_FINAL_PROJECT_SETTING_H
#define COMPUTER_PROGRAMMING_FINAL_PROJECT_SETTING_H


void setting();

#endif //COMPUTER_PROGRAMMING_FINAL_PROJECT_SETTING_H
